const types = {
	REQ_COMPANY_LIST: 'REQ_COMPANY_LIST',
	REQ_TECH_LIST: 'REQ_TECH_LIST',
	STORE_COMPANY_LIST: 'STORE_COMPANY_LIST',
	STORE_TECH_LIST: 'STORE_TECH_LIST',
	ADD_NOTIFICATION: 'ADD_NOTIFICATION',
	REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
}

export default types
