const types = {
  // business data types
  REQ_COMPANY_LIST: 'REQ_COMPANY_LIST',
  REQ_TECH_LIST: 'REQ_TECH_LIST',
  STORE_COMPANY_LIST: 'STORE_COMPANY_LIST',
  STORE_TECH_LIST: 'STORE_TECH_LIST',
  // notification types
  ADD_NOTIFICATION: 'ADD_NOTIFICATION',
  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
  // user data types
  REQ_CURRENT_USER_DATA: 'REQ_CURRENT_USER_DATA',
  STORE_CURRENT_USER_DATA: 'STORE_CURRENT_USER_DATA',
  REQ_CHANGE_STATUS: 'REQ_CHANGE_STATUS',
  STORE_CHANGE_STATUS: 'STORE_CHANGE_STATUS',
  // issue types
  REQ_LOAD_ISSUES: 'REQ_LOAD_ISSUES',
  SUCCESS_LOAD_ISSUES: 'SUCCESS_LOAD_ISSUES',
  ERROR_LOAD_ISSUES: 'ERROR_LOAD_ISSUES',
  REQ_SUBMIT_ISSUE: 'REQ_SUBMIT_ISSUE',
  SUCCESS_SUBMIT_ISSUE: 'SUCCESS_SUBMIT_ISSUE',
  ERROR_SUBMIT_ISSUE: 'ERROR_SUBMIT_ISSUE',
  REQ_CLAIM_ISSUE: 'REQ_CLAIM_ISSUE',
  SUCCESS_CLAIM_ISSUE: 'SUCCESS_CLAIM_ISSUE',
  ERROR_CLAIM_ISSUE: 'ERROR_CLAIM_ISSUE',
  REQ_RESOLVE_ISSUE: 'REQ_RESOLVE_ISSUE',
  SUCCESS_RESOLVE_ISSUE: 'SUCCESS_RESOLVE_ISSUE',
  ERROR_RESOLVE_ISSUE: 'ERROR_RESOLVE_ISSUE',
}

export default types
